-- ARZMOD Costyl Fixes
-- DO NOT EDIT THIS FILE! If you want add own functional, use user.lua
local sampev = require("lib.samp.events")

local orig_sampGetPlayerIdByCharHandle = sampGetPlayerIdByCharHandle
local orig_sampGetCharHandleBySampPlayerId = sampGetCharHandleBySampPlayerId
local orig_sampGetPlayerNickname = sampGetPlayerNickname


local localPlayerId = nil
local localPlayerName = nil

function sampev.onInitGame(playerId)
    localPlayerId = playerId
end


function sampev.onSetPlayerName(playerId, name, success)
    if playerId == localPlayerId and success then
        localPlayerName = name
    end
end


function sampGetPlayerIdByCharHandle(handle)
    local ok, result = orig_sampGetPlayerIdByCharHandle(handle)
    if localPlayerId ~= nil and handle == PLAYER_PED then 
        return true, localPlayerId
    elseif ok then
        return true, result
    else
        return false, nil
    end
end

function sampGetCharHandleBySampPlayerId(playerId)
    local ok, result = orig_sampGetCharHandleBySampPlayerId(playerId)
    if localPlayerId ~= nil and playerId == localPlayerId then 
        return true, PLAYER_PED
    elseif ok then
        return true, result
    else
        return false, nil
    end
end


function sampGetPlayerNickname(playerId)
    local result = orig_sampGetPlayerNickname(playerId)
    if localPlayerId ~= nil and playerId == localPlayerId and localPlayerName ~= nil then 
        return localPlayerName
    else
        return result
    end
end