; Плейлист ST Music — Victor Strand
; [track1]
; title=Название
; url=https://files.catbox.moe/XXXX.mp3

[track1]
title=1AM
url=https://files.catbox.moe/l7ornc.mp3

[track2]
title=Me Pede
url=https://files.catbox.moe/wyoecc.mp3

[track3]
title=Taca a Xereca pra Mim
url=https://files.catbox.moe/m11sdd.mp3

[track4]
title=clocks - slowed + reverb
url=https://files.catbox.moe/uy6hjg.mp3

[track5]
title=Walk
url=https://files.catbox.moe/b9p8zx.mp3

[track6]
title=Heartburn 
url=https://files.catbox.moe/fbc5dx.mp3

[track7]
title=Seve - Slow Version
url=https://files.catbox.moe/j499ck.mp3

[track8]
title=Not Allowed
url=https://files.catbox.moe/2ji7xa.mp3

[track9]
title=prince of egypt 
url=https://files.catbox.moe/mps6kl.mp3

[track10]
title=Maps
url=https://files.catbox.moe/1sbsik.mp3

[track11]
title=Толпы Кричат
url=https://files.catbox.moe/dn7698.mp3

[track12]
title=Disfruto
url=https://files.catbox.moe/6bdtgi.mp3

[track13]
title=Show Me Love
url=https://files.catbox.moe/cs8ube.mp3

[track14]
title=CLEARED - Remix _Slowed
url=https://files.catbox.moe/iuhxu3.mp3

[track15]
title=Formidable
url=https://files.catbox.moe/l1gw7m.mp3

[track16]
title=Forever Young
url=https://files.catbox.moe/ycng0i.mp3

[track17]
title=Elastic Heart
url=https://files.catbox.moe/6d38e9.mp3

[track18]
title=Desliza
url=https://files.catbox.moe/cn4vud.mp3

[track19]
title=Follow You
url=https://files.catbox.moe/2u3xl4.mp3

[track20]
title=Papaoutai
url=https://files.catbox.moe/i507xf.mp3

[track21]
title=Y Que Fue
url=https://files.catbox.moe/7iszov.mp3

[track22]
title=Rocking A Cardigan in Atlanta
url=https://files.catbox.moe/jwqdpj.mp3

[track23]
title=Chocolata _Remix Song
url=https://files.catbox.moe/0mixgv.mp3

[track24]
title=Get Lucky
url=https://files.catbox.moe/rtbmn1.mp3

[track25]
title=Bananza
url=https://files.catbox.moe/whpt5k.mp3

[track26]
title=Go Little Rockstar
url=https://files.catbox.moe/jrld3d.mp3

[track27]
title=Heat Waves - Slowed
url=https://files.catbox.moe/hp7lr2.mp3

[track28]
title=Golden Brown
url=https://files.catbox.moe/rel08s.mp3

[track29]
title=Te Molla
url=https://files.catbox.moe/tfhysx.mp3

[track30]
title=I'm God
url=https://files.catbox.moe/9fvaux.mp3

[track31]
title=Don't Hide (Slowed)
url=https://files.catbox.moe/3ldx76.mp3

[track32]
title=MUEVELOU
url=https://files.catbox.moe/143zsj.mp3

[track33]
title=В Белом Самолете
url=https://files.catbox.moe/afla6e.mp3

[track34]
title=Woman
url=https://files.catbox.moe/igaaeq.mp3

[track35]
title=Endless Summer
url=https://files.catbox.moe/m1yhyl.mp3

[track36]
title=eyudud
url=

[track37]
title=
url=

[track38]
title=
url=

[track39]
title=
url

[track40]
title=
url=